apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- https://github.com/openshift-homeroom/workshop-spawner/resources/overlays/learning-portal?ref=develop

namePrefix: lab-asciidoc-sample-

commonLabels:
  app: lab-asciidoc-sample

configMapGenerator:
- name: spawner-environ
  behavior: merge
  env: settings.sh

patches:
- ingress.yaml
