---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dashboard-cluster-admin
  labels:
    app: dashboard
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
subjects:
  - kind: ServiceAccount
    name: dashboard-user
    namespace: lab-ocp-cns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin

