---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: dashboard
  namespace: lab-ocp-cns
  labels:
    app: dashboard
spec:
  lookupPolicy:
    local: true
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: 'quay.io/geoallen/lab-ocp-cns:latest'
      importPolicy: {scheduled: true}
      referencePolicy:
        type: Source
