---
kind: ServiceAccount
apiVersion: v1
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
    serviceaccounts.openshift.io/oauth-redirectreference.first: >-
      {"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"dashboard"}}
    serviceaccounts.openshift.io/oauth-redirecturi.first: oauth_callback
    serviceaccounts.openshift.io/oauth-want-challenges: 'false'
  name: dashboard-user
  namespace: lab-ocp-cns
  labels:
    app: dashboard
secrets:
  - name: dashboard-user-token
  - name: dashboard-user-dockercfg
imagePullSecrets:
  - name: dashboard-user-dockercfg

