---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: workshop-ocp-odf-admin
  namespace: workshop-ocp-odf-admin
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: workshop
        operator: In
        values:
          - ocp-odf-admin
