---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: lab-ocp-cns
  namespace: lab-ocp-cns
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: lab
        operator: In
        values:
          - ocp-cns
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: lab-ocp-cns
  namespace: openshift-config
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: lab
        operator: In
        values:
          - ocp-cns
