---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: secrets
  namespace: workshop-ocp-odf-admin
spec:
  type: Namespace
  pathname: workshop-ocp-odf-admin
  sourceNamespaces:
    - workshop-ocp-odf-admin
