---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: secrets
  namespace: lab-ocp-cns
spec:
  type: Namespace
  pathname: openshift-config
  sourceNamespaces:
    - lab-ocp-cns
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  annotations:
    apps.open-cluster-management.io/reconcile-rate: low
  name: dashboard
  namespace: lab-ocp-cns
spec:
  type: Git
  pathname: 'https://github.com/purefield/workshop-acm-ocp-odf-admin.git'
