---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-lab-ocp-cns
  namespace: lab-ocp-cns
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: workshop
        operator: In
        values:
          - ocp-odf-admin
