---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-workshop-ocp-odf-admin-auth
  namespace: workshop-ocp-odf-admin
  annotations:
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: PR.AC Identity Management and Access Control
    policy.open-cluster-management.io/controls: PR.AC-4 Access Control
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: policy-workshop-ocp-odf-admin-auth-provider
      spec:
        remediationAction: enforce
        severity: low
        namespaceSelector:
          exclude: ["kube-*"]
          include: ["default"]
        object-templates:
          - complianceType: musthave
            objectDefinition:
              apiVersion: config.openshift.io/v1
              kind: OAuth
              metadata:
                name: cluster
              spec:
                identityProviders:
                  - htpasswd:
                      fileData:
                        name: htpass-secret
                    mappingMethod: claim
                    name: htpasswd
                    type: HTPasswd
                tokenConfig:
                  accessTokenMaxAgeSeconds: 7776000
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-namespace
  namespace: workshop-ocp-odf-admin
placementRef:
  name: placement-workshop-ocp-odf-admin
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: policy-workshop-ocp-odf-admin-auth
  kind: Policy
  apiGroup: policy.open-cluster-management.io
