---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: secrets
  namespace: lab-ocp-cns
  labels:
    workshop: ocp-odf-admin
spec:
  channel: lab-ocp-cns/secrets
  packageFilter:
    annotations:
      secretgroup: workshop-secret
  placement:
    placementRef:
      kind: PlacementRule
      name: placement-lab-ocp-cns
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-path: deployment/
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/reconcile-rate: "off"
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    workshop: ocp-odf-admin
  name: dashboard
  namespace: lab-ocp-cns
spec:
  channel: lab-ocp-cns/dashboard
  placement:
    placementRef:
      kind: PlacementRule
      name: placement-lab-ocp-cns
